### ISSUE TITLE
Getting error " invalid choice: 'jwt' "

### ISSUE THREAD

**Issue by tarkanlar** [teracyhq/httpie-jwt-auth#13]
I installed latest version but getting this error
http: error: argument --auth-type/-A: invalid choice: 'jwt' (choose from 'basic', 'digest')

**Comment by hoatle** [comment]
thank you for your report, let me check and fix this.

**Comment by hoatle** [comment]
@tarkanlar I've checked on both Python 2.7 and Python 3.5, it works.

```
$ pip install httpie
$ pip install httpie-jwt-auth
$ http teracy.com --auth-type=jwt --auth=abc: -v
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer abc
Connection: keep-alive
Host: teracy.com
User-Agent: HTTPie/0.9.6
```

Could you show me the following information?
`$ python --version`, `$ http --version`, `$ http --help`, and then `$ http teracy.com --auth-type=jwt --auth=abc: -v`

Thanks.

**Comment by hoatle** [comment]
@tarkanlar there must be something wrong with your installation. Feel free to reopen this issue if you still can not get it work properly. Thanks.

**Comment by tarkanlar** [comment]
Thanks @hoatle I will try again

**Comment by karousn** [comment]
I have the same error now with :
**python** : 2.7.15rc1
**httpie** : 0.9.8
**message error** : http: error: argument --auth-type/-A: invalid choice: 'jwt' (choose from 'basic', 'digest')

**Comment by hoatle** [comment]
I've checked, works to me on Ubuntu 18.04

```
$ pip install --upgrade pip setuptools # could need to restart the terminal session
$ pip install --upgrade httpie
$ sudo pip install httpie-jwt-auth
$ http teracy.com --auth-type=jwt --auth=abc: -v
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer abc
Connection: keep-alive
Host: teracy.com
User-Agent: HTTPie/1.0.0



HTTP/1.1 302 Moved Temporarily
Connection: keep-alive
Content-Length: 160
Content-Type: text/html
Date: Tue, 20 Nov 2018 14:44:28 GMT
Location: http://blog.teracy.com/
Server: nginx/1.6.2

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

**Comment by karousn** [comment]
my issuer related to https://github.com/jakubroztocil/httpie/issues/566
i use sudo to install httpie and this plugin and it's work now.
Thanks

**Comment by willdzeng** [comment]
Was having the same issue, fixed by removing the system level httpie pacage:
```
sudo apt-get remove httpie 
```
and rerun
```
pip install httpie
pip install httpie-jwt-auth
```
