### ISSUE TITLE
Usage example and quotations marks

### ISSUE THREAD

**Issue by andrgood** [teracyhq/httpie-jwt-auth#15]
System: Windows 10
Build: Latest Stable (0.2.1)

Hello.
In usage example:
`http --auth-type=jwt --auth='<token>:' example.org `

So if i type part after --auth in single quotation marks, i get an invalid token:
`Bearer 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVC`
(this quotation mark should not be after Bearer keyword)

But without quotation marks and with double quotation marks it works fine.

`http --auth-type=jwt --auth=<token>: example.org `
`http --auth-type=jwt --auth="<token>:" example.org `

**Comment by hoatle** [comment]
thank you, I'll update the README with double quotation marks.

related: https://github.com/teracyhq/httpie-jwt-auth/issues/4#issuecomment-268220477

**Comment by hoatle** [comment]
thank you @GoodBoy123, I've updated the README file to use double quotation mark.
