### ISSUE TITLE
Authorization JWT like in curl

### ISSUE THREAD

**Issue by i5ar** [teracyhq/httpie-jwt-auth#26]
Hi,
I'm using django + djangorestframework + djangorestframework-jwt
In **curl** I can get the articles list with the following command:
`curl -H "Authorization: JWT <token>" http://127.0.0.1:8000/api/articles/`
Is there a way to do it with **httpie-jwt-auth**?
I tried the following command with no success:
`http --auth-type=jwt --auth="<token>" http://127.0.0.1:8000/api/articles/ -h` 

    HTTP/1.0 401 Unauthorized
    Allow: GET, HEAD, OPTIONS
    Content-Type: application/json
    Server: WSGIServer/0.2 CPython/3.4.4
    Vary: Accept, Cookie
    WWW-Authenticate: JWT realm="api"
    X-Frame-Options: SAMEORIGIN

**Comment by hoatle** [comment]
please see README.md:

By default, the Bearer prefix auth token is used, you can choose another prefix:

$ JWT_AUTH_PREFIX=JWT && http --auth-type=jwt --auth="<token>" example.org -h

**Comment by hoatle** [comment]
@i5ar it should work and mentioned on README, closed now.

**Comment by i5ar** [comment]
Thanks @hoatle I will try soon.
