### ISSUE TITLE
docs updated with flask_jwt

### ISSUE THREAD

**Issue by satishvis** [teracyhq/httpie-jwt-auth#27]
I was having an issue with using this extension in a flask app.
    http :5000/secret  --auth-type=jwt --auth="Authorization: JWT <token> "
Tried a lot of things. Ultimately this worked
    JWT_AUTH_PREFIX=JWT  JWT_AUTH_TOKEN=<token>  http :5000/secret --auth-type=jwt -v
Thought this may be helpful for someone who is having an issue.
Note: I did not use && between the environmental variables as was mentioned in the docs.

**Comment by hoatle** [comment]
thank you @satishvis, the doc is updated https://github.com/teracyhq/httpie-jwt-auth/commit/e2a887e26b0db3ca1f6aa584fd624d472267a803
