### ISSUE TITLE
should fix failed build from travis-ci

### ISSUE THREAD

**Issue by hoatle** [teracyhq/httpie-jwt-auth#28]
from https://travis-ci.org/teracyhq/httpie-jwt-auth/builds/532613609

**Comment by hieptranquoc** [comment]
@hoatle 
https://github.com/PyCQA/pylint/issues/1960#issuecomment-376114934
Isort currently cleanly supports Python 2.7 and 3.4+ without any dependencies.
So i will remove python 3.3
