### ISSUE TITLE
should not require to have colon character

### ISSUE THREAD

**Issue by hoatle** [teracyhq/httpie-jwt-auth#3]
expected:

```
$ http --auth-type=jwt --auth=jwt_token example.org
```

actual:

```
$ http --auth-type=jwt --auth=jwt_token: example.org
```

**Comment by jkbrzt** [comment]
HTTPie API currently requires a password for auth plugins. It should be changed on our part to allow password or username less authentication schemes. Please feel free to open an issue. 

https://github.com/jkbrzt/httpie/issues/new

**Comment by hoatle** [comment]
thank you @jkbrzt 

issue created: https://github.com/jkbrzt/httpie/issues/378

**Comment by hoatle** [comment]
this is nicer:

```
$ http --auth-type=jwt --token=jwt_token example.org
```

**Comment by hoatle** [comment]
it's nice to be backward compatible with prev httpie-jwt-auth versions (with deprecated warnings)

**Comment by hoatle** [comment]
this requires httpie v0.9.8 and above, so we're going to support these versions https://github.com/jakubroztocil/httpie/blob/master/CHANGELOG.rst#098-2016-12-08
