### ISSUE TITLE
Output is not colored

### ISSUE THREAD

**Issue by gmagno** [teracyhq/httpie-jwt-auth#31]
Hello,

I am not sure this has to do with the plugin, but there seems to be some correlation, so apologies if this is the wrong place to raise this issue.

One of the things I love about HTTPie is the colored output. But for some reason the output of requests using `--auth-type=jwt` are not colorized. I was wondering if this is a missing feature, a bug or silly me doing something wrong.

![image](https://user-images.githubusercontent.com/46817915/69870149-bb487c80-128d-11ea-8448-38eb7f2dfc08.png)

**Comment by datphan** [comment]
I think it is your editor settings, my still works
![image](https://user-images.githubusercontent.com/3851244/73419762-ee24f480-4352-11ea-8058-0ecae05ee5eb.png)

**Comment by hoatle** [comment]
@gmagno could you confirm that it was due to your terminal's settings?

**Comment by gmagno** [comment]
Interesting :thinking: 
It must be something with my fish shell configuration. If I run with bash everything goes smoothly.

![image](https://user-images.githubusercontent.com/46817915/73609219-473a9580-45aa-11ea-97f8-295dfceae469.png)

I guess we can close this issue, thank you for your time.
